#dev 开发环境
server:
  port: 8080


spring:
    datasource:
        name: test
        url: jdbc:mysql://10.100.44.39:3306/zzcvs??useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: zzcvs
        password: zzcvs
        driver-class-name: com.mysql.jdbc.Driver


# 打印sql logs
logging:
  level:
    com.xj.ptgd.dao: DEBUG


mac:
  paw:
    path: ../alnico11/ptgd/src/main/resources/lib/cebkey/

# 9000接口地址
# https://111.205.51.104:3031     --2018-10-19 end
# https://111.205.51.130:3031     --2018-10-23 end
# https://111.205.51.135:3031     -- 现使用
transaction:
  url: https://111.205.51.135:3031

# 反欺诈手机评分 地址
# https://portal.chinacscs.com/SYService/rainScore    (生产)
# http://10.100.40.10:8080/SYService/rainScore        (测试)
rainScore:
  url: http://10.100.40.10:8080/SYService/rainScore

# 被执行人信息查询 地址
# https://portal.chinacscs.com/SYService/underTaker   (生产)
# http://10.100.40.10:8080/SYService/underTaker       (测试)
underTaker:
  url: http://10.100.40.10:8080/SYService/underTaker

fileConfig:
  upFilePath: D:/file
  downloadFilePath: D:/file

# 脚本地址
gdFileDownload:
 url: /root/go/tomcat/